/**
 * git-hooks.mjs
 * Git hooks integration for automatic documentation sync
 */

import fs from 'fs';
import path from 'path';
import { getConfig } from '../core/metadata.mjs';

/**
 * Setup Git post-commit hook for automatic doc detection
 */
export async function setupGitHooks(projectRoot) {
  const gitDir = path.join(projectRoot, '.git');
  const hooksDir = path.join(gitDir, 'hooks');
  const postCommitPath = path.join(hooksDir, 'post-commit');

  // Check if .git exists
  if (!fs.existsSync(gitDir)) {
    console.log('Warning: .git directory not found. Git hooks not installed.');
    return false;
  }

  // Create hooks directory if needed
  if (!fs.existsSync(hooksDir)) {
    fs.mkdirSync(hooksDir, { recursive: true });
  }

  // Read existing post-commit or create new
  let content = '';
  if (fs.existsSync(postCommitPath)) {
    content = fs.readFileSync(postCommitPath, 'utf-8');
  } else {
    content = '#!/bin/bash\n';
  }

  // Check if zywiki hook already exists
  if (content.includes('# ZYWIKI:START')) {
    console.log('Git hooks already configured for zywiki.');
    return true;
  }

  // Get config for docsDir
  const config = getConfig();
  const docsDir = config?.docsDir || 'zywiki';

  // Add zywiki hook section
  const zyWikiHook = `
# ZYWIKI:START - Auto-generated by zywiki
# zywiki documentation sync on commit
if command -v zywiki &> /dev/null; then
  # Detect source code changes
  CHANGED_SRC=$(git diff HEAD~1 --name-only 2>/dev/null | grep -E "^(src|lib|supabase|scripts|tests)/" || true)

  if [ ! -z "$CHANGED_SRC" ]; then
    # Count changed files
    CHANGED_COUNT=$(echo "$CHANGED_SRC" | wc -l | tr -d ' ')

    # Run zywiki detect to check affected docs
    PENDING_COUNT=$(zywiki detect 2>/dev/null | head -1 | grep -o '[0-9]*' || echo "0")

    if [ "$PENDING_COUNT" != "0" ]; then
      echo -e "\\033[0;34m📝 zywiki: $CHANGED_COUNT files changed, $PENDING_COUNT docs need update\\033[0m"

      # Create flag file for Claude Code session
      TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
      mkdir -p .claude
      cat > .claude/auto-docs-update.flag << EOF
{
  "created": "$TIMESTAMP",
  "system": "zywiki",
  "changedFiles": $(echo "$CHANGED_SRC" | head -20 | jq -R -s -c 'split("\\n") | map(select(length > 0))' 2>/dev/null || echo "[]"),
  "pendingCount": $PENDING_COUNT,
  "autoExecute": true,
  "command": "zywiki build"
}
EOF
      echo -e "\\033[0;32m✅ Created .claude/auto-docs-update.flag\\033[0m"
      echo -e "\\033[0;34m   Run 'zywiki build' or wait for Claude Code session\\033[0m"
    fi
  fi
fi
# ZYWIKI:END
`;

  // Append to existing content
  content = content.trim() + '\n' + zyWikiHook;

  // Write file
  fs.writeFileSync(postCommitPath, content);

  // Make executable
  fs.chmodSync(postCommitPath, '755');

  console.log('Git post-commit hook installed for zywiki.');
  return true;
}

/**
 * Remove Git hooks for zywiki
 */
export async function removeGitHooks(projectRoot) {
  const postCommitPath = path.join(projectRoot, '.git', 'hooks', 'post-commit');

  if (!fs.existsSync(postCommitPath)) {
    return true;
  }

  let content = fs.readFileSync(postCommitPath, 'utf-8');

  // Remove zywiki section
  const startMarker = '# ZYWIKI:START';
  const endMarker = '# ZYWIKI:END';
  const regex = new RegExp(`\\n*${startMarker}[\\s\\S]*?${endMarker}\\n*`, 'g');
  content = content.replace(regex, '\n');

  // Write back
  fs.writeFileSync(postCommitPath, content.trim() + '\n');

  console.log('Git hooks removed for zywiki.');
  return true;
}

/**
 * Check if Git hooks are installed
 */
export function hasGitHooks(projectRoot) {
  const postCommitPath = path.join(projectRoot, '.git', 'hooks', 'post-commit');

  if (!fs.existsSync(postCommitPath)) {
    return false;
  }

  const content = fs.readFileSync(postCommitPath, 'utf-8');
  return content.includes('# ZYWIKI:START');
}
